services:
  podly:
    container_name: podly-pure-podcasts
    image: ghcr.io/jdrbc/podly-pure-podcasts:main-lite
    volumes:
      - ./src/instance:/app/src/instance
      - ./src/app/routes/config_routes.py:/app/src/app/routes/config_routes.py
      - ./src/shared:/app/src/shared
      - ./src/podcast_processor:/app/src/podcast_processor
      - ./src/system_prompt.txt:/app/src/system_prompt.txt
    env_file:
      - ./.env.local
    ports:
      - "5001:5001"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:--1}
      - SERVER_THREADS=${SERVER_THREADS:-1}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5001/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: podly-pure-podcasts-network
